on:
  workflow_dispatch:
  schedule:
  - cron: "0 11 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rqthomas/flare-rocker:4.3.2
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
# Point to the right path, run the right Rscript command
      - name: Run automatic prediction file
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SC_AWS_KEY: ${{ secrets.SC_AWS_KEY }}
          SC_AWS_SECRET: ${{ secrets.SC_AWS_SECRET }}
          
        run:  | 
          R -e 'remotes::install_version("RcppRoll", version = "0.3.0")'
          #R -e 'remotes::install_version("xgboost", version = "1.7.7.1")'
          #R -e 'remotes::install_version("tidymodels", version = "1.1.1")'

          /usr/local/bin/r $GITHUB_WORKSPACE/workflows/default/forecast_workflow.R
